name: "Barber"
description: "BARBER"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0

# Bagian konfigurasi Flutter
flutter:
  uses-material-design: true

  # Ini adalah lokasi yang benar untuk assets
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

# ============================================
# INI ADALAH POSISI YANG BENAR
flutter_launcher_icons:
  # 'android: true' CUKUP SATU KALI DI SINI
  android: true 
  ios: true
  
  # Ini untuk iOS dan Android versi lama
  image_path: "assets/images/gobar_icon.png" 

  # --- Bagian untuk Adaptive Icon Android ---
  # 'android: "true"' YANG SEBELUMNYA DI SINI SUDAH DIHAPUS
  # Warna background ungu
  adaptive_icon_background: "#8A2BE2" 

  # Gambar foreground (pastikan background-nya transparan)
  adaptive_icon_foreground: "assets/images/gobar_icon.png"
# ============================================